// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK1mEbCSzzG-1FPvq2NreFEYxsJl518r8',
    appId: '1:519519306752:web:f3a2b4ce033f7fdbde44e5',
    messagingSenderId: '519519306752',
    projectId: 'fir-10fff',
    authDomain: 'fir-10fff.firebaseapp.com',
    storageBucket: 'fir-10fff.appspot.com',
    measurementId: 'G-9K2XJ2YY2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO8sZpAi4FGtOfCjIIdoHTpdmPaigOYyc',
    appId: '1:519519306752:android:d2caea80e268054fde44e5',
    messagingSenderId: '519519306752',
    projectId: 'fir-10fff',
    storageBucket: 'fir-10fff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa--s1wn82IYA93NZyILk4SWwikuwVcdQ',
    appId: '1:519519306752:ios:dec431ae29af5c74de44e5',
    messagingSenderId: '519519306752',
    projectId: 'fir-10fff',
    storageBucket: 'fir-10fff.appspot.com',
    iosBundleId: 'com.example.untitled10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa--s1wn82IYA93NZyILk4SWwikuwVcdQ',
    appId: '1:519519306752:ios:dec431ae29af5c74de44e5',
    messagingSenderId: '519519306752',
    projectId: 'fir-10fff',
    storageBucket: 'fir-10fff.appspot.com',
    iosBundleId: 'com.example.untitled10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK1mEbCSzzG-1FPvq2NreFEYxsJl518r8',
    appId: '1:519519306752:web:1f9da9dda3a98255de44e5',
    messagingSenderId: '519519306752',
    projectId: 'fir-10fff',
    authDomain: 'fir-10fff.firebaseapp.com',
    storageBucket: 'fir-10fff.appspot.com',
    measurementId: 'G-2MSMGTV1X8',
  );
}
